# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orders.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'orders.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0corders.proto\x12\x06orders\"#\n\x0fGetOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"3\n\x08LineItem\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x0b\n\x03qty\x18\x02 \x01(\r\x12\r\n\x05price\x18\x03 \x01(\x01\"E\n\x10GetOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x1f\n\x05items\x18\x02 \x03(\x0b\x32\x10.orders.LineItem\"#\n\x0fGetPriceRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"9\n\x10GetPriceResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x13\n\x0btotal_price\x18\x02 \x01(\x01\x32\x94\x01\n\x14OrdersPricingService\x12=\n\x08GetOrder\x12\x17.orders.GetOrderRequest\x1a\x18.orders.GetOrderResponse\x12=\n\x08GetPrice\x12\x17.orders.GetPriceRequest\x1a\x18.orders.GetPriceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orders_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETORDERREQUEST']._serialized_start=24
  _globals['_GETORDERREQUEST']._serialized_end=59
  _globals['_LINEITEM']._serialized_start=61
  _globals['_LINEITEM']._serialized_end=112
  _globals['_GETORDERRESPONSE']._serialized_start=114
  _globals['_GETORDERRESPONSE']._serialized_end=183
  _globals['_GETPRICEREQUEST']._serialized_start=185
  _globals['_GETPRICEREQUEST']._serialized_end=220
  _globals['_GETPRICERESPONSE']._serialized_start=222
  _globals['_GETPRICERESPONSE']._serialized_end=279
  _globals['_ORDERSPRICINGSERVICE']._serialized_start=282
  _globals['_ORDERSPRICINGSERVICE']._serialized_end=430
# @@protoc_insertion_point(module_scope)
